spring:
  datasource:
    url: jdbc:h2:file:~/h2/testsndb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS liquibase\;CREATE SCHEMA IF NOT EXISTS accounts;
    username: sa
    password: qwe1234
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false